# base azure pipeline for a python project
stages:
  # 'Test' stage to run project test on all branches
  - stage: 'Tests'
    jobs:
      - job: 'Tests'
        pool:
          # use default "Azure Pipelines" pool
          vmImage: 'ubuntu-18.04'
        strategy:
          matrix:
            Python36:
              python.version: '3.6'
            Python37:
              python.version: '3.7'
            Python38:
              python.version: '3.8'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(python.version)'
          - script: 'sudo apt-get install -y socat'
          - script: 'pip install -U tox'
          - script: 'tox -e "py${PYTHON_VERSION//./}"'
